### ISSUE TITLE
lichess_broadcast.py getting values from dict for inexistent keys

### ISSUE THREAD

**Issue by SuperKaninchen** [SuperKaninchen/ChessBroadcaster#1]
After setting everything up and verifying the camera and llichess game are running, lichess_broadcast.py raises an exception upon executing main.py:
```
Traceback (most recent call last):
  File "/home/max/Documents/Chess/ChessBroadcaster/main.py", line 63, in <module>
    broadcast = Broadcast(board_basics, token, broadcast_id, pgn_games, roi_mask, game_id)
  File "/home/max/Documents/Chess/ChessBroadcaster/broadcast.py", line 18, in __init__
    self.internet_broadcast = LichessBroadcast(
  File "/home/max/Documents/Chess/ChessBroadcaster/lichess_broadcast.py", line 29, in __init__
    b_name = broadcast["tour"]["name"]
KeyError: 'tour'
```
when the `broadcast` dict is further inspected, it's clear that these keys don't exist in the current form:
```
<class 'dict'>
{'id': 'a9i3pnQP', 'name': 'Round 1', 'slug': 'round-1', 'url': 'https://lichess.org/broadcast/perfact-test-stream/round-1/a9i3pnQP', 'games': [{'id': '9yy8ZlDr', 'name': 'Chapter 1', 'url': 'https://lichess.org/broadcast/perfact-test-stream/round-1/a9i3pnQP/9yy8ZlDr'}]}
```
code in `lichess_broadcast.py` is possibly outdated, looking into it

**Comment by SuperKaninchen** [comment]
changed a few lines in `lichess_broadcast.py` by removing the `["tour"]` and changing `["rounds"]` to `["games"]`.
Program now successfully finds broadcast, however, it raises a new exception:
```
Found broadcast: Round 1
Traceback (most recent call last):
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/exceptions.py", line 63, in _catch_exception
    response.raise_for_status()
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/broadcast/round/9yy8ZlDr/push

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/max/Documents/Chess/ChessBroadcaster/main.py", line 63, in <module>
    broadcast = Broadcast(board_basics, token, broadcast_id, pgn_games, roi_mask, game_id)
  File "/home/max/Documents/Chess/ChessBroadcaster/broadcast.py", line 18, in __init__
    self.internet_broadcast = LichessBroadcast(
  File "/home/max/Documents/Chess/ChessBroadcaster/lichess_broadcast.py", line 40, in __init__
    self.round_setup()
  File "/home/max/Documents/Chess/ChessBroadcaster/lichess_broadcast.py", line 49, in round_setup
    self.client.broadcasts.push_pgn_update(
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/clients.py", line 1085, in push_pgn_update
    return self._r.post(path, data=games)['ok']
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/session.py", line 64, in post
    return self.request('POST', *args, **kwargs)
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/session.py", line 54, in request
    raise exceptions.ResponseError(response)
berserk.exceptions.ResponseError: HTTP 404: Not Found: {'error': 'Not found'}

```

**Comment by SuperKaninchen** [comment]
turns out the url called by berserk is wrong: `https://lichess.org/broadcast/round/9yy8ZlDr/push` should probably be `https://lichess.org/broadcast/perfact-test-stream/round-1/a9i3pnQP/9yy8ZlDr/push` (the url from the broadcast dict)
Berserk source for reference:
```python
def push_pgn_update(self, broadcast_id, pgn_games, slug='-'):
  """Manually update an existing broadcast by ID.
  
  :param str broadcast_id: ID of a broadcast
  :param list pgn_games: one or more games in PGN format
  :return: success
  :rtype: bool
  """
  path = f'broadcast/{slug}/{broadcast_id}/push'
  games = '\n\n'.join(g.strip() for g in pgn_games)
  return self._r.post(path, data=games)['ok']
```
This method is being called with `slug="round", broadcast_id="9yy8Z1Dr"`, which results in the faulty url.

**Comment by SuperKaninchen** [comment]
turns out I was wrong
```
Traceback (most recent call last):
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/exceptions.py", line 63, in _catch_exception
    response.raise_for_status()
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/broadcast/perfact-test-stream/round-1/a9i3pnQP/9yy8ZlDr/push

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/max/Documents/Chess/ChessBroadcaster/main.py", line 63, in <module>
    broadcast = Broadcast(board_basics, token, broadcast_id, pgn_games, roi_mask, game_id)
  File "/home/max/Documents/Chess/ChessBroadcaster/broadcast.py", line 18, in __init__
    self.internet_broadcast = LichessBroadcast(
  File "/home/max/Documents/Chess/ChessBroadcaster/lichess_broadcast.py", line 46, in __init__
    self.round_setup()
  File "/home/max/Documents/Chess/ChessBroadcaster/lichess_broadcast.py", line 55, in round_setup
    self.client.broadcasts.push_pgn_update(
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/clients.py", line 1085, in push_pgn_update
    return self._r.post(path, data=games)['ok']
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/session.py", line 64, in post
    return self.request('POST', *args, **kwargs)
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/session.py", line 54, in request
    raise exceptions.ResponseError(response)
berserk.exceptions.ResponseError: 404 Client Error: Not Found for url: https://lichess.org/broadcast/perfact-test-stream/round-1/a9i3pnQP/9yy8ZlDr/push
```
looking into which url to actually call

**Comment by SuperKaninchen** [comment]
okay, so according to the [Lichess API Docs](https://lichess.org/api#tag/Broadcasts/operation/broadcastPush) the url should look like this:
```
https://lichess.org/broadcast/round/{broadcastRoundId}/push
```
meaning the initial url was correct, but it still responds with 404

**Comment by SuperKaninchen** [comment]
moving this to new issue as dict key issue has been resolved
