### ISSUE TITLE
Berserk raises HTTP 404 Exception

### ISSUE THREAD

**Issue by SuperKaninchen** [SuperKaninchen/ChessBroadcaster#2]
even though the url is correct according to the [Lichess API Docs](https://lichess.org/api#tag/Broadcasts/operation/broadcastPush), it still errors out:
```
Found broadcast: Round 1
Traceback (most recent call last):
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/exceptions.py", line 63, in _catch_exception
    response.raise_for_status()
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://lichess.org/broadcast/round/9yy8ZlDr/push

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/max/Documents/Chess/ChessBroadcaster/main.py", line 63, in <module>
    broadcast = Broadcast(board_basics, token, broadcast_id, pgn_games, roi_mask, game_id)
  File "/home/max/Documents/Chess/ChessBroadcaster/broadcast.py", line 18, in __init__
    self.internet_broadcast = LichessBroadcast(
  File "/home/max/Documents/Chess/ChessBroadcaster/lichess_broadcast.py", line 41, in __init__
    self.round_setup()
  File "/home/max/Documents/Chess/ChessBroadcaster/lichess_broadcast.py", line 50, in round_setup
    self.client.broadcasts.push_pgn_update(
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/clients.py", line 1085, in push_pgn_update
    return self._r.post(path, data=games)['ok']
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/session.py", line 64, in post
    return self.request('POST', *args, **kwargs)
  File "/home/max/Documents/Chess/chess_env/lib/python3.10/site-packages/berserk/session.py", line 54, in request
    raise exceptions.ResponseError(response)
berserk.exceptions.ResponseError: HTTP 404: Not Found: {'error': 'Not found'}
```

**Comment by SuperKaninchen** [comment]
disabled online interactions in f290b5c
works as expected

**Comment by gandie** [comment]
Btw, can u add me as collaborator so i dont need to fork this again? Would love to help :rocket:

**Comment by SuperKaninchen** [comment]
> Btw, can u add me as collaborator so i dont need to fork this again? Would love to help rocket

done, have fun untangling the spaghetti

**Comment by tttiago** [comment]
Hello! I tried to access the broadcast URL https://lichess.org/broadcast/round/9yy8ZlDr in a browser and it gives a blank page. 
It should return the broadcast page if it existed. So I believe that you are trying to push the moves to a broadcast that does not exist and thus the error.
Can you verify that you have created a broadcast and its ID is 9yy8ZlDr?

**Comment by SuperKaninchen** [comment]
Hi, the broadcast id should be [`a9i3pnQP`](https://lichess.org/broadcast/round/a9i3pnQP), `9yy8ZIDr` is the round id I found inside the broadcast dict

**Comment by tttiago** [comment]
Sorry, my mistake.
I presume you were able to get the round id using the code below with no problems
```
self.broadcast = broadcast["tour"]
self.round_id = broadcast["rounds"][-1 if not round else round]["id"]
```
Does your lichess token have the necessary permissions to write to the broadcast?

**Comment by SuperKaninchen** [comment]
Nope, it wasn't that simple, for some reason my dict looks different from yours (see #1 )

**Comment by tttiago** [comment]
I believe you got the round dict instead of the broadcast dict. 
If you check the lichess API, your dict has the same strucuture as https://lichess.org/api#tag/Broadcasts/operation/broadcastRoundGet instead of https://lichess.org/api#tag/Broadcasts/operation/broadcastTourGet.
I believe you set `broadcast_id` in the `broadcast_info.py` file to the `broadcastRoundId` of Round 1 of your broadcast instead of passing the `broadcastTournamentId` of the tournament.

**Comment by SuperKaninchen** [comment]
The broadcast_info.py file contains `a9i3pnQP` as the broadcast id.
Turns out there are 3 unique IDs, `F27WZgWt` is the new one which should be correct. The documentation on that part is kinda confusing for someone who never used lichess before, as it simply says "You can get the id by going to the tournament settings of the broadcast", which I interpreted as clicking on 
![image](https://user-images.githubusercontent.com/16620882/205041339-8bdeae25-bf40-4689-abf5-ad2c0fb69c80.png)
and not first clicking on 
![image](https://user-images.githubusercontent.com/16620882/205041426-0fa583b0-132c-461f-8cae-43c700a9994a.png)
and then on
![image](https://user-images.githubusercontent.com/16620882/205041482-2af31eb3-6c54-4bd1-95d6-07163a46a9e5.png)

**Comment by tttiago** [comment]
You are right, the instructions were not clear. I updated the README to try to make it clearer. Thank you for your feedback!
